import { db } from '@/db';
import { blogPosts } from '@/db/schema';

async function main() {
    const sampleBlogPosts = [
        // Design Category (3 posts)
        {
            title: '10 UI Design Trends That Will Dominate 2024',
            slug: '10-ui-design-trends-that-will-dominate-2024',
            content: 'The digital design landscape is constantly evolving, and 2024 is set to bring some exciting changes to UI design. From bold typography to immersive 3D elements, designers are pushing boundaries like never before. Understanding these trends is crucial for staying competitive in the digital space.\n\nOne of the most prominent trends we\'re seeing is the rise of neumorphism 2.0, which combines soft shadows with vibrant gradients to create depth and dimension. This evolution of the original neumorphic design addresses earlier accessibility concerns while maintaining the aesthetic appeal. Additionally, micro-interactions are becoming more sophisticated, providing users with delightful feedback that enhances the overall experience.\n\nAnother significant trend is the integration of AI-generated design elements. Tools like Midjourney and DALL-E are empowering designers to create unique visual assets quickly, allowing more time for strategic thinking and user experience optimization. The key is to use AI as a tool to enhance creativity, not replace it.\n\nAs we move forward, the focus on accessibility and inclusive design will only intensify. Dark mode options, reduced motion preferences, and high-contrast themes are no longer optional—they\'re essential. Designers who embrace these trends while maintaining strong fundamentals will create the most impactful digital experiences in 2024.',
            excerpt: 'Discover the top UI design trends shaping 2024, from neumorphism 2.0 to AI-powered design elements. Learn how to implement these trends while maintaining accessibility and user experience at the forefront.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5',
            category: 'Design',
            authorName: 'Priya Sharma',
            authorId: 1,
            publishedAt: new Date('2024-01-15').toISOString(),
            readTime: 8,
            status: 'published',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'The Psychology of Color in Web Design',
            slug: 'the-psychology-of-color-in-web-design',
            content: 'Color is one of the most powerful tools in a designer\'s arsenal, capable of evoking emotions, driving actions, and creating memorable brand experiences. Understanding color psychology is essential for creating websites that not only look beautiful but also convert visitors into customers.\n\nDifferent colors trigger different emotional responses. Blue conveys trust and professionalism, which is why it\'s favored by financial institutions and tech companies. Red creates urgency and excitement, making it perfect for calls-to-action and sale announcements. Green is associated with growth and harmony, often used by environmental and wellness brands. The key is choosing colors that align with your brand values and resonate with your target audience.\n\nColor contrast is equally important for both aesthetics and accessibility. A well-chosen color palette ensures readability across devices and helps users with visual impairments navigate your site effectively. Tools like WebAIM\'s contrast checker can help you maintain WCAG compliance while creating visually stunning designs.\n\nCultural context also plays a crucial role in color selection. While white symbolizes purity in Western cultures, it represents mourning in some Eastern cultures. When designing for a global audience, research cultural color associations to avoid unintended messages. The most successful websites use color strategically, creating visual hierarchy and guiding users through their journey with intentional color choices.',
            excerpt: 'Explore how color psychology influences user behavior and learn to create effective color palettes that enhance user experience while maintaining brand consistency and accessibility standards.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab',
            category: 'Design',
            authorName: 'Alex Mitchell',
            authorId: 2,
            publishedAt: new Date('2024-03-22').toISOString(),
            readTime: 7,
            status: 'published',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        {
            title: 'Typography Best Practices for Modern Websites',
            slug: 'typography-best-practices-for-modern-websites',
            content: 'Typography is the backbone of web design, yet it\'s often overlooked in favor of flashy graphics and animations. Good typography enhances readability, establishes visual hierarchy, and reinforces brand identity. In 2024, mastering typography is more important than ever as users consume content across an increasingly diverse range of devices.\n\nThe foundation of great typography starts with choosing the right typeface. Sans-serif fonts like Inter, Outfit, and Poppins have become standard for body text due to their excellent readability on screens. For headings, consider display fonts that add personality while maintaining legibility. The key is limiting yourself to 2-3 typefaces maximum—too many fonts create visual chaos and slow down your site.\n\nFont sizing and spacing are crucial for creating comfortable reading experiences. Body text should be at least 16px on desktop and 18px on mobile. Line height (leading) should be 1.5 to 1.8 times the font size, and paragraph spacing should be larger than line spacing to clearly separate ideas. These seemingly small details significantly impact how long users stay engaged with your content.\n\nResponsive typography goes beyond simply scaling font sizes. Modern CSS features like clamp() allow for fluid typography that adapts smoothly across breakpoints. Variable fonts offer even more flexibility, letting you fine-tune weight and width for different contexts. By implementing these best practices, you\'ll create websites that are not only beautiful but also functional and accessible to all users.',
            excerpt: 'Master the art of web typography with these essential best practices. Learn how to choose typefaces, optimize readability, and implement responsive typography that works across all devices.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4',
            category: 'Design',
            authorName: 'Rahul Verma',
            authorId: 3,
            publishedAt: new Date('2024-06-08').toISOString(),
            readTime: 9,
            status: 'published',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },
        // Marketing Category (3 posts)
        {
            title: 'SEO Strategies for Small Business Success in 2024',
            slug: 'seo-strategies-for-small-business-success-2024',
            content: 'Search engine optimization remains one of the most cost-effective marketing strategies for small businesses. However, the SEO landscape has evolved dramatically, with Google\'s algorithm updates emphasizing user experience, content quality, and E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) more than ever before.\n\nLocal SEO should be your first priority as a small business. Claim and optimize your Google Business Profile with accurate information, high-quality photos, and regular posts. Encourage satisfied customers to leave reviews and respond to all feedback professionally. Local citations across directories like Yelp, Bing Places, and industry-specific platforms help establish your business\'s legitimacy and improve local search rankings.\n\nContent marketing is no longer optional—it\'s essential. Create valuable, in-depth content that answers your customers\' questions and solves their problems. Focus on long-tail keywords that reflect actual search intent rather than chasing high-volume competitive terms. Blog posts, how-to guides, and case studies not only attract organic traffic but also position you as an industry expert.\n\nTechnical SEO can\'t be ignored either. Ensure your website loads quickly, is mobile-friendly, and has a clear site structure. Use schema markup to help search engines understand your content better. Regular technical audits catch issues before they impact rankings. Remember, SEO is a marathon, not a sprint—consistent effort over months yields sustainable results that paid advertising simply can\'t match.',
            excerpt: 'Discover proven SEO strategies tailored for small businesses. Learn how to dominate local search, create content that ranks, and implement technical optimizations that drive organic growth.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
            category: 'Marketing',
            authorName: 'Sarah Chen',
            authorId: 4,
            publishedAt: new Date('2024-02-10').toISOString(),
            readTime: 10,
            status: 'published',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Content Strategy: Building Your Brand Through Storytelling',
            slug: 'content-strategy-building-brand-through-storytelling',
            content: 'In an era of information overload, storytelling has become the differentiator between brands that connect with audiences and those that get ignored. A well-crafted content strategy leverages storytelling to create emotional connections, build trust, and ultimately drive business results.\n\nStart by defining your brand narrative. What\'s your origin story? What problems do you solve? What values drive your business? Your content should consistently reinforce these themes across all channels. Nike doesn\'t just sell shoes—they sell the idea of athletic achievement. Apple doesn\'t just sell technology—they sell innovation and creativity. Your brand story should be equally compelling and authentic.\n\nContent pillars provide structure to your storytelling. Identify 3-5 core themes that resonate with your audience and align with your business goals. For a digital agency, these might include design inspiration, marketing tips, client success stories, industry insights, and team culture. Each piece of content should tie back to one of these pillars, creating a cohesive narrative over time.\n\nDistribution is as important as creation. The best content means nothing if it doesn\'t reach your audience. Use a multi-channel approach: publish long-form content on your blog, repurpose it into social media posts, create video summaries for YouTube, and develop email newsletters. Track performance metrics to understand what resonates, then double down on what works. Great content strategy is iterative, data-driven, and always evolving.',
            excerpt: 'Learn how to develop a content strategy that tells your brand story effectively. Discover frameworks for creating compelling content that engages audiences and drives measurable business results.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1542435503-956c469947f6',
            category: 'Marketing',
            authorName: 'Priya Sharma',
            authorId: 1,
            publishedAt: new Date('2024-04-18').toISOString(),
            readTime: 8,
            status: 'published',
            createdAt: new Date('2024-04-12').toISOString(),
            updatedAt: new Date('2024-04-18').toISOString(),
        },
        {
            title: 'Social Media Marketing: Trends and Tactics That Actually Work',
            slug: 'social-media-marketing-trends-and-tactics-that-work',
            content: 'Social media marketing continues to evolve rapidly, with new platforms, features, and algorithm changes keeping marketers on their toes. Success in 2024 requires staying agile while focusing on authentic engagement rather than vanity metrics like follower counts.\n\nShort-form video content dominates across platforms. TikTok\'s influence has pushed Instagram Reels, YouTube Shorts, and even LinkedIn to prioritize video. The key is creating entertaining, educational content that stops the scroll. Behind-the-scenes footage, quick tips, and trending audio can significantly boost reach. Don\'t aim for perfection—authenticity performs better than polished corporate content.\n\nCommunity building should be your top priority. Respond to comments, engage with your audience\'s content, and create opportunities for two-way conversations. Private Facebook groups, LinkedIn communities, and Discord servers allow for deeper connections beyond public posts. These engaged communities become brand advocates who amplify your message organically.\n\nPaid social advertising requires sophistication. Generic boost-post strategies won\'t cut it anymore. Use detailed targeting, compelling creatives, and strategic retargeting to maximize ROI. Test different ad formats, copy variations, and audience segments. The Facebook pixel and conversion APIs provide crucial data for optimization. Remember, organic reach is declining—smart brands allocate budget to paid promotion while building genuine community engagement.',
            excerpt: 'Navigate the ever-changing social media landscape with proven strategies. Learn how to leverage short-form video, build engaged communities, and run effective paid campaigns that deliver ROI.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113',
            category: 'Marketing',
            authorName: 'Alex Mitchell',
            authorId: 2,
            publishedAt: new Date('2024-08-25').toISOString(),
            readTime: 9,
            status: 'published',
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        // Tech Category (3 posts)
        {
            title: 'How to Build a Scalable Next.js Application',
            slug: 'how-to-build-scalable-nextjs-application',
            content: 'Next.js has become the go-to framework for building modern React applications, offering server-side rendering, static site generation, and a fantastic developer experience out of the box. However, building a scalable application requires thoughtful architecture and best practices from the start.\n\nProject structure is foundational. Organize your codebase with feature-based folders rather than grouping by file type. Keep components, hooks, utilities, and tests together in feature folders. This approach makes code easier to navigate as your application grows. Use the app directory for Next.js 13+ with server components by default, only marking components as client components when necessary for interactivity.\n\nData fetching strategies significantly impact performance. Use React Server Components to fetch data on the server, reducing JavaScript sent to the client. Implement proper caching strategies with Next.js revalidation options. For frequently changing data, consider using SWR or React Query for client-side caching and optimistic updates. Always show loading states to maintain a responsive feel even when data takes time to load.\n\nCode splitting happens automatically in Next.js, but you can optimize further. Use dynamic imports for heavy components that aren\'t needed immediately. Lazy load images with the next/image component, which also provides automatic optimization. Monitor your bundle size regularly with tools like @next/bundle-analyzer. A scalable application is one that loads quickly regardless of how many features you add over time.',
            excerpt: 'Master Next.js development with this comprehensive guide to building scalable applications. Learn best practices for project structure, data fetching, performance optimization, and more.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c',
            category: 'Tech',
            authorName: 'Rahul Verma',
            authorId: 3,
            publishedAt: new Date('2024-01-28').toISOString(),
            readTime: 11,
            status: 'published',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Modern React Patterns Every Developer Should Know',
            slug: 'modern-react-patterns-every-developer-should-know',
            content: 'React continues to evolve, introducing new patterns and best practices that make our code more maintainable and performant. Staying current with these patterns is essential for writing production-ready applications that scale.\n\nCompound components provide flexibility while maintaining encapsulation. Instead of passing dozens of props to configure a component, compound components use context to share state between parent and children. This pattern is evident in libraries like Radix UI and Headless UI. It creates more intuitive APIs and gives consumers control over markup while keeping implementation details hidden.\n\nCustom hooks are your secret weapon for code reuse. Extract common logic like data fetching, form handling, or localStorage management into custom hooks. Name them with the "use" prefix and ensure they follow hooks rules. Well-designed custom hooks make your components cleaner and your codebase more maintainable. Don\'t repeat yourself—if you\'re writing similar logic in multiple components, it\'s time for a custom hook.\n\nPerformance optimization starts with understanding when components re-render. Use React DevTools Profiler to identify unnecessary renders. Memoize expensive computations with useMemo and expensive callbacks with useCallback, but only when profiling shows they\'re needed. Premature optimization wastes time—measure first, optimize second. Proper state management, avoiding prop drilling with context, and lazy loading features are usually more impactful than micro-optimizations.',
            excerpt: 'Elevate your React skills with modern patterns including compound components, custom hooks, and performance optimization techniques. Learn when and how to apply these patterns in real-world applications.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee',
            category: 'Tech',
            authorName: 'Sarah Chen',
            authorId: 4,
            publishedAt: new Date('2024-05-12').toISOString(),
            readTime: 10,
            status: 'published',
            createdAt: new Date('2024-05-05').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        {
            title: 'AI-Powered Web Development: Tools and Techniques for 2024',
            slug: 'ai-powered-web-development-tools-and-techniques-2024',
            content: 'Artificial intelligence is revolutionizing web development, offering tools that enhance productivity, improve code quality, and enable entirely new capabilities. Understanding how to leverage AI effectively is becoming as important as knowing your framework of choice.\n\nAI coding assistants like GitHub Copilot, Cursor, and Amazon CodeWhisperer have moved beyond simple autocomplete. They understand context, suggest entire functions, and even write tests. The key is treating them as pair programming partners rather than replacement developers. Review suggestions critically, understand the generated code, and customize it for your specific needs. These tools excel at boilerplate code and common patterns, freeing you to focus on complex problem-solving.\n\nAI-powered testing is transforming quality assurance. Tools can generate test cases, identify edge cases developers might miss, and even predict where bugs are likely to occur based on code patterns. Automated accessibility testing using AI can catch issues that traditional linters miss. However, AI testing complements rather than replaces human testing—user experience and business logic still require human judgment.\n\nEmbed AI capabilities directly into your applications using APIs from OpenAI, Anthropic, or open-source models. Implement features like intelligent search, content generation, code explanation, or chatbots. The serverless architecture of platforms like Vercel and Netlify makes deploying AI-powered features straightforward. As AI tools mature, the competitive advantage goes to developers who integrate them effectively while maintaining code quality and security.',
            excerpt: 'Explore how AI is transforming web development in 2024. Learn to leverage AI coding assistants, implement intelligent features, and use AI-powered testing to build better applications faster.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995',
            category: 'Tech',
            authorName: 'Priya Sharma',
            authorId: 1,
            publishedAt: new Date('2024-09-30').toISOString(),
            readTime: 12,
            status: 'published',
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-30').toISOString(),
        },
        // Tips Category (3 posts)
        {
            title: 'Mastering Client Communication as a Freelancer',
            slug: 'mastering-client-communication-as-freelancer',
            content: 'Effective communication is the difference between freelancers who struggle and those who thrive. Technical skills get you in the door, but communication skills build lasting client relationships and generate referrals. Mastering client communication transforms one-time projects into ongoing partnerships.\n\nSet clear expectations from the start. Define scope, deliverables, timelines, and payment terms in writing before starting work. Use project management tools like Notion, Asana, or ClickUp to keep everyone aligned. Weekly progress updates prevent surprises and demonstrate professionalism. When problems arise—and they will—communicate early. Clients appreciate transparency and proactive problem-solving far more than radio silence followed by excuses.\n\nLearn to speak your client\'s language. Technical jargon impresses other developers, not clients. Translate complex concepts into business outcomes they care about: increased conversions, reduced costs, improved user experience. Ask questions to understand their business goals, not just project requirements. Clients hire you for expertise, so don\'t hesitate to push back on bad ideas with better alternatives backed by reasoning.\n\nDocumentation saves relationships. Keep detailed records of decisions, approvals, and changes. Use tools like Loom for screen recordings when explaining complex topics. Written communication creates accountability and prevents "I never said that" situations. Schedule regular check-ins rather than waiting for clients to reach out. Proactive communication builds trust and positions you as a partner invested in their success, not just a vendor completing tasks.',
            excerpt: 'Transform your freelance career with effective client communication strategies. Learn how to set expectations, handle difficult conversations, and build long-term relationships that generate recurring revenue.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1552581234-26160f608093',
            category: 'Tips',
            authorName: 'Alex Mitchell',
            authorId: 2,
            publishedAt: new Date('2024-03-05').toISOString(),
            readTime: 8,
            status: 'published',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            title: 'Productivity Hacks for Remote Digital Professionals',
            slug: 'productivity-hacks-for-remote-digital-professionals',
            content: 'Remote work offers incredible flexibility, but it also presents unique productivity challenges. Distractions multiply, boundaries blur, and isolation can impact motivation. Implementing the right systems and habits is crucial for maintaining high performance while working from home.\n\nCreate a dedicated workspace that signals "work mode" to your brain. This doesn\'t require a full home office—even a specific corner of your kitchen table works if it\'s consistent. Invest in ergonomic equipment: a good chair, external monitor, and keyboard make hours of work more comfortable. Natural light, plants, and minimal clutter improve focus and mood. When you sit in your workspace, your brain knows it\'s time to work.\n\nTime blocking revolutionizes productivity. Instead of reacting to whatever feels urgent, schedule focused blocks for deep work, meetings, email, and breaks. Use techniques like Pomodoro (25-minute focus sessions) for tasks requiring concentration. Protect your morning hours for challenging creative work when mental energy is highest. Schedule meetings in clusters to preserve long stretches of uninterrupted time. Your calendar should reflect your priorities, not just other people\'s requests.\n\nSystemize routine decisions to preserve mental energy. Create templates for common communications, standardize your tech stack, and automate repetitive tasks with tools like Zapier or n8n. Use keyboard shortcuts and snippet tools like TextExpander to save countless keystrokes. The time invested in systems pays dividends daily. Finally, respect boundaries—log off at a consistent time, take real breaks, and protect your personal time as fiercely as your work time.',
            excerpt: 'Maximize your productivity as a remote worker with proven strategies for workspace design, time management, and automation. Learn how to maintain focus and work-life balance in a home environment.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b',
            category: 'Tips',
            authorName: 'Rahul Verma',
            authorId: 3,
            publishedAt: new Date('2024-07-14').toISOString(),
            readTime: 9,
            status: 'published',
            createdAt: new Date('2024-07-08').toISOString(),
            updatedAt: new Date('2024-07-14').toISOString(),
        },
        {
            title: 'Building a Profitable Digital Agency: Lessons from the Trenches',
            slug: 'building-profitable-digital-agency-lessons-from-trenches',
            content: 'Starting a digital agency is exciting, but building a profitable, sustainable business requires more than design skills and hustle. After years of experience, we\'ve learned what separates agencies that thrive from those that struggle month to month.\n\nSpecialization beats generalization. "We do everything" appeals to you but confuses potential clients. Pick a niche—e-commerce websites, SaaS startups, healthcare, real estate—and become the obvious choice for that market. Specialized positioning allows premium pricing, makes marketing easier, and creates systems you can repeat. You\'ll learn industry-specific challenges deeply and build case studies that resonate with ideal clients.\n\nValue-based pricing transforms profitability. Hourly billing caps your income and incentivizes inefficiency. Instead, price based on the value you deliver: increased revenue, reduced costs, or competitive advantage. A website that generates $100K in new business is worth far more than the 40 hours you spent building it. Have pricing conversations early, anchor to business outcomes, and don\'t apologize for your rates. Clients who balk at value-based fees probably aren\'t ideal clients anyway.\n\nSystems and delegation enable growth. Document your processes for everything—client onboarding, design workflow, development standards, project management. Hire specialists before you think you\'re ready. Your agency scales when you\'re working on the business, not in the business. Invest in project management tools, time tracking, and financial management. Review metrics monthly: profit margins, project profitability, client acquisition cost, lifetime value. Data-driven decisions separate hobby agencies from real businesses.',
            excerpt: 'Learn the essential strategies for building a profitable digital agency. Discover how specialization, value-based pricing, and systems thinking create sustainable growth and recurring revenue.',
            thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40',
            category: 'Tips',
            authorName: 'Sarah Chen',
            authorId: 4,
            publishedAt: new Date('2024-11-20').toISOString(),
            readTime: 10,
            status: 'published',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
    ];

    await db.insert(blogPosts).values(sampleBlogPosts);
    
    console.log('✅ Blog posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});