import { db } from '@/db';
import { serviceItems } from '@/db/schema';

async function main() {
    const sampleServiceItems = [
        // Service 5 (Digital Marketing) - serviceId: 5
        {
            serviceId: 5,
            icon: 'Search',
            title: 'SEO',
            items: ["On-page optimization", "Keyword research", "Technical SEO", "Link building"],
            displayOrder: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 5,
            icon: 'MapPin',
            title: 'Local SEO',
            items: ["Google My Business", "Local citations", "Location-based optimization", "Review management"],
            displayOrder: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 5,
            icon: 'Instagram',
            title: 'Social Media Management',
            items: ["Content strategy", "Daily posting", "Community engagement", "Analytics reporting"],
            displayOrder: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 5,
            icon: 'Target',
            title: 'PPC Management',
            items: ["Google Ads", "Facebook Ads", "Campaign optimization", "ROI tracking"],
            displayOrder: 4,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 5,
            icon: 'Users',
            title: 'Influencer Marketing',
            items: ["Influencer outreach", "Campaign coordination", "Performance tracking", "Brand partnerships"],
            displayOrder: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Service 6 (Web Development) - serviceId: 6
        {
            serviceId: 6,
            icon: 'Layout',
            title: 'Front-End Development',
            items: ["React.js", "Next.js", "Responsive design", "Modern UI/UX"],
            displayOrder: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 6,
            icon: 'Database',
            title: 'Backend Development',
            items: ["Node.js", "API development", "Database design", "Server configuration"],
            displayOrder: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 6,
            icon: 'ShoppingCart',
            title: 'Ecommerce Development',
            items: ["Shopping cart", "Payment integration", "Product management", "Order tracking"],
            displayOrder: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 6,
            icon: 'Globe',
            title: 'WordPress Development',
            items: ["Custom themes", "Plugin development", "WooCommerce setup", "SEO optimization"],
            displayOrder: 4,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 6,
            icon: 'Package',
            title: 'Shopify Development',
            items: ["Theme customization", "App integration", "Store setup", "Performance optimization"],
            displayOrder: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Service 7 (Mobile App Development) - serviceId: 7
        {
            serviceId: 7,
            icon: 'Smartphone',
            title: 'iOS Development',
            items: ["Swift", "Native features", "App Store submission", "Performance optimization"],
            displayOrder: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 7,
            icon: 'Tablet',
            title: 'Android Development',
            items: ["Kotlin/Java", "Material Design", "Play Store deployment", "Cross-device compatibility"],
            displayOrder: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 7,
            icon: 'Code',
            title: 'React Native Development',
            items: ["Cross-platform apps", "Code reusability", "Native performance", "Fast deployment"],
            displayOrder: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 7,
            icon: 'Zap',
            title: 'Flutter Development',
            items: ["Beautiful UI", "Hot reload", "High performance", "Single codebase"],
            displayOrder: 4,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Service 8 (Server) - serviceId: 8
        {
            serviceId: 8,
            icon: 'Server',
            title: 'Shared Hosting',
            items: ["cPanel access", "Email accounts", "SSL certificate", "24/7 monitoring"],
            displayOrder: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 8,
            icon: 'HardDrive',
            title: 'VPS Server',
            items: ["Dedicated resources", "Root access", "Scalable infrastructure", "Full control"],
            displayOrder: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 8,
            icon: 'Share2',
            title: 'Reseller Hosting',
            items: ["White-label hosting", "Multiple cPanel accounts", "Billing management", "Technical support"],
            displayOrder: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Service 9 (Creative Designing) - serviceId: 9
        {
            serviceId: 9,
            icon: 'Image',
            title: 'Photo Editing',
            items: ["Retouching", "Color correction", "Background removal", "Image enhancement"],
            displayOrder: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 9,
            icon: 'Layers',
            title: 'UI UX Design',
            items: ["User research", "Wireframing", "Prototyping", "Usability testing"],
            displayOrder: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 9,
            icon: 'Award',
            title: 'Branding',
            items: ["Logo design", "Brand guidelines", "Visual identity", "Brand strategy"],
            displayOrder: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 9,
            icon: 'Film',
            title: 'Banner Ad Designing',
            items: ["Display ads", "Social media banners", "Animated banners", "A/B testing"],
            displayOrder: 4,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 9,
            icon: 'Camera',
            title: 'Social Media Graphics',
            items: ["Instagram posts", "Facebook covers", "LinkedIn graphics", "Story templates"],
            displayOrder: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Service 10 (Video Production) - serviceId: 10
        {
            serviceId: 10,
            icon: 'Video',
            title: 'Promotional Video',
            items: ["Product showcase", "Brand videos", "Commercial ads", "Video editing"],
            displayOrder: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 10,
            icon: 'PlayCircle',
            title: 'Explainer Video',
            items: ["Animated explainers", "Whiteboard animation", "Voiceover", "Script writing"],
            displayOrder: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 10,
            icon: 'Briefcase',
            title: 'Corporate Video',
            items: ["Company profile", "Training videos", "Event coverage", "Testimonials"],
            displayOrder: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 10,
            icon: 'Film',
            title: '2D 3D Animated Ad Video',
            items: ["Motion graphics", "Character animation", "3D modeling", "Visual effects"],
            displayOrder: 4,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            serviceId: 10,
            icon: 'Cpu',
            title: 'AI Video & More',
            items: ["AI-powered editing", "Automated subtitles", "Video enhancement", "Deep learning effects"],
            displayOrder: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(serviceItems).values(sampleServiceItems);
    
    console.log('✅ Service items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});